// <auto-generated />
using System;
using GeotecnologiaKNS.Geo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeotecnologiaKNS.Geo.Migrations
{
    [DbContext(typeof(GeoDbContext))]
    [Migration("20261004023814_SituacaoDoCarPorExtenso")]
    partial class SituacaoDoCarPorExtenso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("geo")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.CamadaReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoReferencia")
                        .HasColumnType("integer")
                        .HasColumnName("ano_referencia");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTime?>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("chave");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("origem");

                    b.Property<int?>("PeriodicidadeDias")
                        .HasColumnType("integer")
                        .HasColumnName("periodicidade_dias");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int>("TotalFeicoes")
                        .HasColumnType("integer")
                        .HasColumnName("total_feicoes");

                    b.Property<int>("VersaoAtual")
                        .HasColumnType("integer")
                        .HasColumnName("versao_atual");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.HasIndex("Tipo");

                    b.ToTable("camada_referencia", "geo");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.CargaBaseCar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("arquivo");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluida_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("HashArquivo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_arquivo");

                    b.Property<DateTime>("IniciadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciada_em");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("origem");

                    b.Property<int>("RegistrosDescartados")
                        .HasColumnType("integer")
                        .HasColumnName("registros_descartados");

                    b.Property<int>("RegistrosGravados")
                        .HasColumnType("integer")
                        .HasColumnName("registros_gravados");

                    b.Property<int>("RegistrosLidos")
                        .HasColumnType("integer")
                        .HasColumnName("registros_lidos");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("carga_base_car", "geo");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.CoberturaMunicipio", b =>
                {
                    b.Property<string>("CodigoIbge")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_ibge");

                    b.Property<long>("CargaId")
                        .HasColumnType("bigint")
                        .HasColumnName("carga_id");

                    b.Property<DateTime>("CobertoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("coberto_em");

                    b.Property<int>("Imoveis")
                        .HasColumnType("integer")
                        .HasColumnName("imoveis");

                    b.Property<string>("Municipio")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("municipio");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("CodigoIbge");

                    b.HasIndex("CargaId");

                    b.HasIndex("Uf");

                    b.ToTable("cobertura_municipio", "geo");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.FeicaoReferencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AtributosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("atributos");

                    b.Property<int>("CamadaId")
                        .HasColumnType("integer")
                        .HasColumnName("camada_id");

                    b.Property<Geometry>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry,4326)")
                        .HasColumnName("geometria");

                    b.Property<string>("Rotulo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("rotulo");

                    b.Property<int>("Versao")
                        .HasColumnType("integer")
                        .HasColumnName("versao");

                    b.HasKey("Id");

                    b.HasIndex("Geometria");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometria"), "gist");

                    b.HasIndex("CamadaId", "Versao")
                        .HasDatabaseName("ix_feicao_camada_versao");

                    b.ToTable("feicao_referencia", "geo");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.ImovelCar", b =>
                {
                    b.Property<string>("CodigoCar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_car");

                    b.Property<double?>("AreaCalculadaHa")
                        .HasColumnType("double precision")
                        .HasColumnName("area_calculada_ha");

                    b.Property<double?>("AreaHa")
                        .HasColumnType("double precision")
                        .HasColumnName("area_ha");

                    b.Property<DateTime?>("AtualizadoEmOrigem")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em_origem");

                    b.Property<long>("CargaId")
                        .HasColumnType("bigint")
                        .HasColumnName("carga_id");

                    b.Property<Point>("Centroide")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("centroide");

                    b.Property<string>("CodigoIbge")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_ibge");

                    b.Property<string>("Municipio")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("municipio");

                    b.Property<Geometry>("Perimetro")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry,4326)")
                        .HasColumnName("perimetro");

                    b.Property<string>("Situacao")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("situacao");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("CodigoCar");

                    b.HasIndex("CargaId");

                    b.HasIndex("Perimetro");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Perimetro"), "gist");

                    b.HasIndex("Uf");

                    b.ToTable("imovel_car", "geo");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.LacunaCobertura", b =>
                {
                    b.Property<string>("CodigoIbge")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_ibge");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Consultas")
                        .HasColumnType("integer")
                        .HasColumnName("consultas");

                    b.Property<DateTime>("PrimeiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("primeira_em");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<DateTime>("UltimaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_em");

                    b.Property<string>("UltimoCodigoCar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ultimo_codigo_car");

                    b.HasKey("CodigoIbge", "TenantId");

                    b.HasIndex("UltimaEm");

                    b.ToTable("lacuna_cobertura", "geo");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.ListaRestritiva", b =>
                {
                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("origem");

                    b.Property<int?>("PeriodicidadeDias")
                        .HasColumnType("integer")
                        .HasColumnName("periodicidade_dias");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("integer")
                        .HasColumnName("total_registros");

                    b.Property<int>("VersaoAtual")
                        .HasColumnType("integer")
                        .HasColumnName("versao_atual");

                    b.HasKey("Tipo");

                    b.ToTable("lista_restritiva", "geo");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.RestricaoDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CarregadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("carregado_em");

                    b.Property<string>("DataRestricao")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("data_restricao");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Municipio")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("municipio");

                    b.Property<string>("NomeTitular")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome_titular");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("origem");

                    b.Property<string>("Referencia")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("referencia");

                    b.Property<bool>("TemGeometria")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_geometria");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<int>("Versao")
                        .HasColumnType("integer")
                        .HasColumnName("versao");

                    b.HasKey("Id");

                    b.HasIndex("Documento", "Tipo", "Versao")
                        .HasDatabaseName("ix_restricao_documento");

                    b.ToTable("restricao_documento", "geo");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.CoberturaMunicipio", b =>
                {
                    b.HasOne("GeotecnologiaKNS.Geo.Entities.CargaBaseCar", "Carga")
                        .WithMany()
                        .HasForeignKey("CargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carga");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.FeicaoReferencia", b =>
                {
                    b.HasOne("GeotecnologiaKNS.Geo.Entities.CamadaReferencia", "Camada")
                        .WithMany("Feicoes")
                        .HasForeignKey("CamadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camada");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.ImovelCar", b =>
                {
                    b.HasOne("GeotecnologiaKNS.Geo.Entities.CargaBaseCar", "Carga")
                        .WithMany("Imoveis")
                        .HasForeignKey("CargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carga");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.CamadaReferencia", b =>
                {
                    b.Navigation("Feicoes");
                });

            modelBuilder.Entity("GeotecnologiaKNS.Geo.Entities.CargaBaseCar", b =>
                {
                    b.Navigation("Imoveis");
                });
#pragma warning restore 612, 618
        }
    }
}
