global using static GeotecnologiaKNS.Utils.Global;
global using GeotecnologiaKNS.Data;
global using GeotecnologiaKNS.Repositories.Interfaces;
global using GeotecnologiaKNS.Repositories;
global using Microsoft.AspNetCore;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using GeotecnologiaKNS.Models;
global using GeotecnologiaKNS;
global using GeotecnologiaKNS.Utils;
global using GeotecnologiaKNS.Infra;
